"""MFS Class A ticker aliases for name-keyed tax PDFs.

The 2025 ``mfs_cg_fly.pdf`` book is % of NAV with fund + share-class labels and
no ticker column. Class A / All Classes rows stay name-slug keyed. Class B/C/I/R
names map to their own official product-page tickers (not Class A). Product-page
Class A rows that already parse MIGHX / MFEGX / … keep those tickers
(enrichment never overwrites). Massachusetts Investors Growth R3 is MIGHX —
already used on the Class A book row, so that R3 name is left unmapped.

Sources: MFS Class A performance book
https://www.mfs.com/content/dam/mfs-enterprise/mfscom/products/performance/perf_mfd.pdf
and Class A product pages (MRGAX, MWEFX, MAMAX, MAAGX, MIEJX, MFFSX, …).
"""

from __future__ import annotations

# (ticker, fund_identifier or None, names, cusip or None)
MFS_FUND_ROWS: tuple[tuple[str, str | None, tuple[str, ...], str | None], ...] = (
    # Already ticker-keyed Class A product pages — All Classes % NAV rows only
    ("MFEGX", None, ("MFS Growth Fund All Classes",), None),
    ("MEIAX", None, ("MFS Value Fund All Classes",), None),
    ("MSFRX", None, ("MFS Total Return Fund All Classes",), None),
    ("MMUFX", None, ("MFS Utilities Fund All Classes",), None),
    ("MVCAX", None, ("MFS Mid Cap Value Fund All Classes",), None),
    ("MNDAX", None, ("MFS New Discovery Fund All Classes",), None),
    ("MGRAX", None, ("MFS International Growth Fund All Classes",), None),
    # Remaining Class A / All Classes names
    (
        "MRGAX",
        None,
        ("MFS Core Equity Fund Class A", "MFS Core Equity Fund"),
        None,
    ),
    (
        "MWEFX",
        None,
        ("MFS Global Equity Fund Class A", "MFS Global Equity Fund"),
        None,
    ),
    (
        "MWOFX",
        None,
        ("MFS Global Growth Fund Class A", "MFS Global Growth Fund"),
        None,
    ),
    (
        "MAMAX",
        None,
        ("MFS Moderate Allocation Fund Class A", "MFS Moderate Allocation Fund"),
        None,
    ),
    ("MUEAX", None, ("MFS Blended Research Core Equity Fund Class A", "MFS Blended Research Core Equity Fund"), None),
    ("BRKAX", None, ("MFS Blended Research Emerging Markets Equity Fund All Classes",), None),
    ("BRWAX", None, ("MFS Blended Research Growth Equity Fund All Classes",), None),
    ("BRXAX", None, ("MFS Blended Research International Equity Fund All Classes",), None),
    ("BMSFX", None, ("MFS Blended Research Mid Cap Equity Fund All Classes",), None),
    ("BRSDX", None, ("MFS Blended Research Small Cap Equity Fund All Classes",), None),
    ("BRUDX", None, ("MFS Blended Research Value Equity Fund All Classes",), None),
    ("MFALX", None, ("MFS Alabama Municipal Bond Fund All Classes",), None),
    ("MFARX", None, ("MFS Arkansas Municipal Bond Fund All Classes",), None),
    ("MCFTX", None, ("MFS California Municipal Bond Fund All Classes",), None),
    ("MMGAX", None, ("MFS Georgia Municipal Bond Fund All Classes",), None),
    ("MFSMX", None, ("MFS Maryland Municipal Bond Fund All Classes",), None),
    ("MFSSX", None, ("MFS Massachusetts Municipal Bond Fund All Classes",), None),
    ("MISSX", None, ("MFS Mississippi Municipal Bond Fund All Classes",), None),
    ("MSNYX", None, ("MFS New York Municipal Bond Fund All Classes",), None),
    ("MSNCX", None, ("MFS North Carolina Municipal Bond Fund All Classes",), None),
    ("MFPAX", None, ("MFS Pennsylvania Municipal Bond Fund All Classes",), None),
    ("MFSCX", None, ("MFS South Carolina Municipal Bond Fund All Classes",), None),
    ("MSVAX", None, ("MFS Virginia Municipal Bond Fund All Classes",), None),
    ("MFWVX", None, ("MFS West Virginia Municipal Bond Fund All Classes",), None),
    ("MCSAX", None, ("MFS Commodity Strategy Fund All Classes",), None),
    ("MACFX", None, ("MFS Conservative Allocation Fund All Classes",), None),
    ("MAGWX", None, ("MFS Growth Allocation Fund All Classes",), None),
    ("MAAGX", None, ("MFS Aggressive Growth Allocation Fund All Classes",), None),
    ("MCBEX", None, ("MFS Core Bond Fund All Classes",), None),
    ("MFBFX", None, ("MFS Corporate Bond Fund All Classes",), None),
    ("DIFAX", None, ("MFS Diversified Income Fund All Classes",), None),
    ("MEDAX", None, ("MFS Emerging Markets Debt Fund All Classes",), None),
    ("EMLAX", None, ("MFS Emerging Markets Debt Local Currency Fund All Classes",), None),
    ("MEMAX", None, ("MFS Emerging Markets Equity Fund All Classes",), None),
    ("EEMPX", None, ("MFS Emerging Markets Equity Research Fund All Classes",), None),
    ("EQNAX", None, ("MFS Equity Income Fund All Classes",), None),
    ("DVRAX", None, ("MFS Global Alternative Strategy Fund All Classes",), None),
    ("MHOAX", None, ("MFS Global High Yield Fund All Classes",), None),
    ("GLNAX", None, ("MFS Global New Discovery Fund All Classes",), None),
    ("MGBAX", None, ("MFS Global Opportunistic Bond Fund All Classes",), None),
    ("MGLAX", None, ("MFS Global Real Estate Fund All Classes",), None),
    ("MFWTX", None, ("MFS Global Total Return Fund All Classes",), None),
    ("MFGSX", None, ("MFS Government Securities Fund All Classes",), None),
    ("MHITX", None, ("MFS High Income Fund All Classes",), None),
    ("MFIOX", None, ("MFS Income Fund All Classes",), None),
    ("MIAAX", None, ("MFS Inflation-Adjusted Bond Fund All Classes",), None),
    ("MDIDX", None, ("MFS International Diversification Fund All Classes",), None),
    ("MIEJX", None, ("MFS International Equity Fund All Classes",), None),
    ("MKVBX", None, ("MFS International Large Cap Value Fund All Classes",), None),
    ("MIDAX", None, ("MFS International New Discovery Fund All Classes",), None),
    ("UIVVX", None, ("MFS Intrinsic Value Fund All Classes",), None),
    ("LTTAX", None, ("MFS Lifetime 2025 Fund All Classes",), None),
    ("MLTAX", None, ("MFS Lifetime 2030 Fund All Classes",), None),
    ("LFEAX", None, ("MFS Lifetime 2035 Fund All Classes",), None),
    ("MLFAX", None, ("MFS Lifetime 2040 Fund All Classes",), None),
    ("LTMAX", None, ("MFS Lifetime 2045 Fund All Classes",), None),
    ("MFFSX", None, ("MFS Lifetime 2050 Fund All Classes",), None),
    ("LFIAX", None, ("MFS Lifetime 2055 Fund All Classes",), None),
    ("MFJAX", None, ("MFS Lifetime 2060 Fund All Classes",), None),
    ("LFTFX", None, ("MFS Lifetime 2065 Fund All Classes",), None),
    ("MLLAX", None, ("MFS Lifetime Income Fund All Classes",), None),
    ("MQLFX", None, ("MFS Limited Maturity Fund All Classes",), None),
    ("MLVAX", None, ("MFS Low Volatility Equity Fund All Classes",), None),
    ("MVGAX", None, ("MFS Low Volatility Global Equity Fund All Classes",), None),
    ("MNWAX", None, ("MFS Managed Wealth Fund All Classes",), None),
    ("MMHYX", None, ("MFS Municipal High Income Fund All Classes",), None),
    ("MFIAX", None, ("MFS Municipal Income Fund All Classes",), None),
    ("MIUAX", None, ("MFS Municipal Intermediate Fund All Classes",), None),
    ("MTLFX", None, ("MFS Municipal Limited Maturity Fund All Classes",), None),
    ("NDVAX", None, ("MFS New Discovery Value Fund All Classes",), None),
    ("MRSAX", None, ("MFS Research International Fund All Classes",), None),
    ("MRBFX", None, ("MFS Total Return Bond Fund All Classes",), None),
    # Wave 13 — official product-page share-class identifiers (not Class A).
    ("MUSBX", None, ("MFS Blended Research Core Equity Fund Class B",), None),
    ("MUECX", None, ("MFS Blended Research Core Equity Fund Class C",), None),
    ("MUSEX", None, ("MFS Blended Research Core Equity Fund Class I",), None),
    ("MUERX", None, ("MFS Blended Research Core Equity Fund Class R1 shares",), None),
    ("MUESX", None, ("MFS Blended Research Core Equity Fund Class R2 shares",), None),
    ("MUETX", None, ("MFS Blended Research Core Equity Fund Class R3 shares",), None),
    ("MUEUX", None, ("MFS Blended Research Core Equity Fund Class R4 shares",), None),
    ("MUEVX", None, ("MFS Blended Research Core Equity Fund Class R6 shares",), None),
    ("MRGBX", None, ("MFS Core Equity Fund Class B",), None),
    ("MRGCX", None, ("MFS Core Equity Fund Class C",), None),
    ("MRGRX", None, ("MFS Core Equity Fund Class I",), None),
    ("MRGGX", None, ("MFS Core Equity Fund Class R1 shares",), None),
    ("MRERX", None, ("MFS Core Equity Fund Class R2 shares",), None),
    ("MRGHX", None, ("MFS Core Equity Fund Class R3 shares",), None),
    ("MRGJX", None, ("MFS Core Equity Fund Class R4 shares",), None),
    ("MRGKX", None, ("MFS Core Equity Fund Class R6 shares",), None),
    ("MWEBX", None, ("MFS Global Equity Fund Class B",), None),
    ("MWECX", None, ("MFS Global Equity Fund Class C",), None),
    ("MWEIX", None, ("MFS Global Equity Fund Class I",), None),
    ("MWEGX", None, ("MFS Global Equity Fund Class R1 shares",), None),
    ("MEQRX", None, ("MFS Global Equity Fund Class R2 shares",), None),
    ("MWEHX", None, ("MFS Global Equity Fund Class R3 shares",), None),
    ("MWELX", None, ("MFS Global Equity Fund Class R4 shares",), None),
    ("MWEMX", None, ("MFS Global Equity Fund Class R6 shares",), None),
    ("MWOBX", None, ("MFS Global Growth Fund Class B",), None),
    ("MWOCX", None, ("MFS Global Growth Fund Class C",), None),
    ("MWOIX", None, ("MFS Global Growth Fund Class I",), None),
    ("MWOGX", None, ("MFS Global Growth Fund Class R1 shares",), None),
    ("MGWRX", None, ("MFS Global Growth Fund Class R2 shares",), None),
    ("MWOHX", None, ("MFS Global Growth Fund Class R3 shares",), None),
    ("MWOJX", None, ("MFS Global Growth Fund Class R4 shares",), None),
    ("MWOKX", None, ("MFS Global Growth Fund Class R6 shares",), None),
    ("MEGBX", None, ("MFS Growth Fund Class B",), None),
    ("MFECX", None, ("MFS Growth Fund Class C",), None),
    ("MFEIX", None, ("MFS Growth Fund Class I",), None),
    ("MFELX", None, ("MFS Growth Fund Class R1 shares",), None),
    ("MEGRX", None, ("MFS Growth Fund Class R2 shares",), None),
    ("MFEHX", None, ("MFS Growth Fund Class R3 shares",), None),
    ("MFEJX", None, ("MFS Growth Fund Class R4 shares",), None),
    ("MFEKX", None, ("MFS Growth Fund Class R6 shares",), None),
    ("MGIBX", None, ("MFS International Intrinsic Value Fund Class B",), None),
    ("MGICX", None, ("MFS International Intrinsic Value Fund Class C",), None),
    ("MINIX", None, ("MFS International Intrinsic Value Fund Class I",), None),
    ("MINRX", None, ("MFS International Intrinsic Value Fund Class R1 shares",), None),
    ("MINFX", None, ("MFS International Intrinsic Value Fund Class R2 shares",), None),
    ("MINGX", None, ("MFS International Intrinsic Value Fund Class R3 shares",), None),
    ("MINHX", None, ("MFS International Intrinsic Value Fund Class R4 shares",), None),
    ("MINJX", None, ("MFS International Intrinsic Value Fund Class R6 shares",), None),
    ("OTCBX", None, ("MFS Mid Cap Growth Fund Class B",), None),
    ("OTCCX", None, ("MFS Mid Cap Growth Fund Class C",), None),
    ("OTCIX", None, ("MFS Mid Cap Growth Fund Class I",), None),
    ("OTCGX", None, ("MFS Mid Cap Growth Fund Class R1 shares",), None),
    ("MCPRX", None, ("MFS Mid Cap Growth Fund Class R2 shares",), None),
    ("OTCHX", None, ("MFS Mid Cap Growth Fund Class R3 shares",), None),
    ("OTCJX", None, ("MFS Mid Cap Growth Fund Class R4 shares",), None),
    ("OTCKX", None, ("MFS Mid Cap Growth Fund Class R6 shares",), None),
    ("MMABX", None, ("MFS Moderate Allocation Fund Class B",), None),
    ("MMACX", None, ("MFS Moderate Allocation Fund Class C",), None),
    ("MMAIX", None, ("MFS Moderate Allocation Fund Class I",), None),
    ("MAMFX", None, ("MFS Moderate Allocation Fund Class R1 shares",), None),
    ("MARRX", None, ("MFS Moderate Allocation Fund Class R2 shares",), None),
    ("MAMHX", None, ("MFS Moderate Allocation Fund Class R3 shares",), None),
    ("MAMJX", None, ("MFS Moderate Allocation Fund Class R4 shares",), None),
    ("MAMPX", None, ("MFS Moderate Allocation Fund Class R6 shares",), None),
    ("MFRBX", None, ("MFS Research Fund Class B",), None),
    ("MFRCX", None, ("MFS Research Fund Class C",), None),
    ("MRFIX", None, ("MFS Research Fund Class I",), None),
    ("MFRLX", None, ("MFS Research Fund Class R1 shares",), None),
    ("MSRRX", None, ("MFS Research Fund Class R2 shares",), None),
    ("MFRHX", None, ("MFS Research Fund Class R3 shares",), None),
    ("MFRJX", None, ("MFS Research Fund Class R4 shares",), None),
    ("MFRKX", None, ("MFS Research Fund Class R6 shares",), None),
    ("MTCBX", None, ("MFS Technology Fund Class B",), None),
    ("MTCCX", None, ("MFS Technology Fund Class C",), None),
    ("MTCIX", None, ("MFS Technology Fund Class I",), None),
    ("MTCKX", None, ("MFS Technology Fund Class R1 shares",), None),
    ("MTERX", None, ("MFS Technology Fund Class R2 shares",), None),
    ("MTCHX", None, ("MFS Technology Fund Class R3 shares",), None),
    ("MTCJX", None, ("MFS Technology Fund Class R4 shares",), None),
    ("MTCLX", None, ("MFS Technology Fund Class R6 shares",), None),
    ("MIGBX", None, ("Massachusetts Investors Growth Stock Fund Class B",), None),
    ("MIGDX", None, ("Massachusetts Investors Growth Stock Fund Class C",), None),
    ("MGTIX", None, ("Massachusetts Investors Growth Stock Fund Class I",), None),
    ("MIGMX", None, ("Massachusetts Investors Growth Stock Fund Class R1 shares",), None),
    ("MIRGX", None, ("Massachusetts Investors Growth Stock Fund Class R2 shares",), None),
    ("MIGKX", None, ("Massachusetts Investors Growth Stock Fund Class R4 shares",), None),
    ("MIGNX", None, ("Massachusetts Investors Growth Stock Fund Class R6 shares",), None),
)
