"""Top-40 Aftertax coverage readiness: estimate feeds, YE history, performance.

Status strings are for GET /coverage and the weekly scrape contract.
Do not invent estimate amounts when a wired hub is empty or seasonal.
"""

from __future__ import annotations

# prelim/updated already in fixtures or live HTML that parses estimates.
# paid_history_only: estimate hub is wired for weekly walk but current book is paid/final.
# deferred: SPA/403 still walked; no invented zeros.
# skipped: reserved; Amundi / Pioneer is included per Eric 2026-09-08.
ESTIMATE_STATUS: dict[str, str] = {
    "blackrock": "prelim_updated",
    "vanguard": "paid_history_only",
    "fidelity": "prelim_updated",
    "state_street": "deferred",
    "jpmorgan": "prelim_updated",
    "goldman_sachs": "deferred",
    "american_funds": "prelim_updated",
    "pimco": "deferred",
    "invesco": "prelim_updated",
    "t_rowe_price": "prelim_updated",
    "ubs": "prelim_updated",
    "franklin_templeton": "deferred",
    "bny_mellon": "prelim_updated",
    "nuveen": "prelim_updated",
    "northern_trust": "prelim_updated",
    "morgan_stanley": "paid_history_only",
    "schwab": "paid_history_only",
    "dimensional": "prelim_updated",
    "columbia_threadneedle": "prelim_updated",
    "amundi": "prelim_updated",
    "allspring": "paid_history_only",
    "janus_henderson": "prelim_updated",
    "american_century": "prelim_updated",
    "dodge_cox": "prelim_updated",
    "mfs": "prelim_updated",
    "lord_abbett": "prelim_updated",
    "ab": "prelim_updated",
    "federated_hermes": "prelim_updated",
    "virtus": "prelim_updated",
    "eaton_vance": "deferred",
    "john_hancock": "prelim_updated",
    "principal": "paid_history_only",
    "thrivent": "paid_history_only",
    "hartford": "prelim_updated",
    "macquarie": "prelim_updated",
    "first_eagle": "prelim_updated",
    "gmo": "prelim_updated",
    "artisan": "paid_history_only",
    "calamos": "prelim_updated",
    "wasatch": "prelim_updated",
    "harbor": "prelim_updated",
    "nationwide": "paid_history_only",
    "voya": "prelim_updated",
    "oakmark": "paid_history_only",
    "tweedy": "prelim_updated",
    "gabelli": "paid_history_only",
    "royce": "paid_history_only",
    "nylife": "prelim_updated",
    "touchstone": "paid_history_only",
    "victory": "prelim_updated",
    "sei": "prelim_updated",
    "brown_advisory": "prelim_updated",
    "william_blair": "paid_history_only",
    "vaneck": "prelim_updated",
    "wisdomtree": "prelim_updated",
    "first_trust": "prelim_updated",
    "dws": "prelim_updated",
    "aqr": "prelim_updated",
    "causeway": "paid_history_only",
    "alger": "paid_history_only",
    "harding_loevner": "paid_history_only",
    "matthews_asia": "paid_history_only",
    "tcw": "paid_history_only",
    "bridgeway": "prelim_updated",
    "jensen": "paid_history_only",
    "diamond_hill": "prelim_updated",
    "champlain": "paid_history_only",
    "driehaus": "paid_history_only",
    "hotchkis": "paid_history_only",
    "marsico": "paid_history_only",
    "osterweis": "prelim_updated",
    "davis": "paid_history_only",
    "primecap": "prelim_updated",
    "ariel": "paid_history_only",
    "baird": "paid_history_only",
    "longleaf": "paid_history_only",
    "buffalo": "prelim_updated",
    "gqg": "prelim_updated",
    "third_avenue": "paid_history_only",
    "heartland": "paid_history_only",
    "fmi": "paid_history_only",
    "impax": "deferred",
    "american_beacon": "paid_history_only",
    "baillie_gifford": "prelim_updated",
    "brandes": "prelim_updated",
    "mairs_power": "paid_history_only",
    "boston_trust": "paid_history_only",
    "grandeur_peak": "paid_history_only",
    "hennessy": "paid_history_only",
    "fam": "paid_history_only",
    "meridian": "paid_history_only",
    "kinetics": "paid_history_only",
    "lazard": "prelim_updated",
    "manning_napier": "paid_history_only",
    "westwood": "prelim_updated",
    "boston_partners": "prelim_updated",
    "homestead": "paid_history_only",
    "madison": "prelim_updated",
    "lsv": "paid_history_only",
    "lkcm": "prelim_updated",
    "oberweis": "paid_history_only",
    "riverpark": "paid_history_only",
    "amg": "paid_history_only",
    "guidestone": "prelim_updated",
    "value_line": "paid_history_only",
    "permanent_portfolio": "paid_history_only",
    "conestoga": "prelim_updated",
    "kopernik": "paid_history_only",
    "locorr": "paid_history_only",
    "timothy_plan": "paid_history_only",
    "hodges": "prelim_updated",
    "tocqueville": "paid_history_only",
}

# Calendar years with official YE/paid/estimate fixtures (not invented).
HISTORY_YEARS: dict[str, tuple[int, ...]] = {
    "blackrock": (2021, 2022, 2023, 2024, 2025, 2026),
    "vanguard": (2021, 2022, 2023, 2024, 2025),
    "fidelity": (2024, 2025, 2026),
    "state_street": (2021, 2022, 2023, 2024, 2025),
    "jpmorgan": (2024, 2025),
    "goldman_sachs": (2025,),
    "american_funds": (2021, 2022, 2023, 2024, 2025, 2026),
    "pimco": (),
    "invesco": (2024, 2025),
    "t_rowe_price": (2021, 2022, 2023, 2024, 2025),
    "ubs": (2025,),
    "franklin_templeton": (2024, 2025),
    "bny_mellon": (2022, 2023, 2024, 2025),
    "nuveen": (2025,),
    "northern_trust": (2021, 2022, 2023, 2024, 2025),
    "morgan_stanley": (2024, 2025),
    "schwab": (2021, 2022, 2023, 2024, 2025),
    "dimensional": (2024, 2025),
    "columbia_threadneedle": (2024, 2025),
    "amundi": (2023, 2024, 2025),
    "allspring": (2021, 2022, 2023, 2024, 2025),
    "janus_henderson": (2021, 2022, 2023, 2024, 2025),
    "american_century": (2022, 2023, 2025),
    "dodge_cox": (2021, 2022, 2023, 2024, 2025, 2026),
    "mfs": (2021, 2022, 2023, 2024, 2025, 2026),
    "lord_abbett": (2025,),
    "ab": (2023, 2025),
    "federated_hermes": (2025,),
    "virtus": (2024, 2025, 2026),
    "eaton_vance": (2025,),
    "john_hancock": (2022, 2023, 2024, 2025),
    "principal": (2023, 2024, 2025),
    "thrivent": (2024, 2025),
    "hartford": (2024, 2025),
    "macquarie": (2023, 2024, 2025),
    "first_eagle": (2023, 2024, 2025),
    "gmo": (2025, 2026),
    "artisan": (2024, 2025, 2026),
    "calamos": (2024, 2025),
    "wasatch": (2022, 2024, 2025),
    "harbor": (2025,),
    "nationwide": (2025,),
    "voya": (2024, 2025),
    "oakmark": (2024, 2025),
    "tweedy": (2024, 2025),
    "gabelli": (2024, 2025),
    "royce": (2024, 2025),
    "nylife": (2025,),
    "touchstone": (2025,),
    "victory": (2024, 2025),
    "sei": (2024, 2025),
    "brown_advisory": (2024, 2025),
    "william_blair": (2024, 2025),
    "vaneck": (2023, 2024, 2025),
    "wisdomtree": (2024, 2025),
    "first_trust": (2025,),
    "dws": (2025, 2026),
    "aqr": (2024, 2025),
    "causeway": (2024, 2025),
    "alger": (2025,),
    "harding_loevner": (2025,),
    "matthews_asia": (2021, 2022, 2023, 2024, 2025),
    "tcw": (2025,),
    "bridgeway": (2024, 2025),
    "jensen": (2024, 2025),
    "diamond_hill": (2024, 2025),
    "champlain": (2025,),
    "driehaus": (2025,),
    "hotchkis": (2025,),
    "marsico": (2025,),
    "osterweis": (2025,),
    "davis": (2025,),
    "primecap": (2025,),
    "ariel": (2025,),
    "baird": (2025,),
    "longleaf": (2025,),
    "buffalo": (2025,),
    "gqg": (2025,),
    "third_avenue": (2025,),
    "heartland": (2025,),
    "fmi": (2025,),
    "impax": (2025,),
    "american_beacon": (2025,),
    "baillie_gifford": (2025,),
    "brandes": (2025,),
    "mairs_power": (2025,),
    "boston_trust": (2025,),
    "grandeur_peak": (2025,),
    "hennessy": (2025,),
    "fam": (2025,),
    "meridian": (2025,),
    "kinetics": (2025,),
    "lazard": (2025,),
    "manning_napier": (2025,),
    "westwood": (2025,),
    "boston_partners": (2025,),
    "homestead": (2025,),
    "madison": (2025,),
    "lsv": (2025,),
    "lkcm": (2025,),
    "oberweis": (2025,),
    "riverpark": (2025,),
    "amg": (2025,),
    "guidestone": (2025,),
    "value_line": (2025,),
    "permanent_portfolio": (2025,),
    "conestoga": (2026,),
    "kopernik": (2025,),
    "locorr": (2025,),
    "timothy_plan": (2025,),
    "hodges": (2025,),
    "tocqueville": (2025,),
}

# Tickers with Growth of $X fixtures (Yahoo monthly adj close).
PERFORMANCE_TICKERS: dict[str, tuple[str, ...]] = {
    "blackrock": ("MDDVX", "AGG"),
    "vanguard": ("VFIAX", "VTIAX", "VIGAX", "VBIAX", "VXUS"),
    "fidelity": ("FBGRX",),
    "state_street": ("SPY", "ALLW"),
    "american_funds": ("AGTHX", "AMCPX", "ABALX"),
    "t_rowe_price": ("TRBCX",),
    "schwab": ("SWTSX", "SWANX"),
    "dodge_cox": ("DODIX", "DODGX"),
    "janus_henderson": ("JDCAX",),
    "northern_trust": ("NOSIX",),
    "amundi": ("PIODX", "PIGFX"),
    "first_eagle": ("SGENX", "FEVAX", "FEGE", "FEOE", "FEFAX"),
    "harbor": ("HACAX", "HAVLX"),
    "nationwide": ("NWHOX",),
    "voya": ("NLCAX",),
    "oakmark": ("OAKMX",),
    "tweedy": ("TBGVX",),
    "gabelli": ("GABGX",),
    "royce": ("RYTRX",),
    "victory": ("MMEAX", "VETAX"),
    "amg": ("YACKX",),
    "brown_advisory": ("BAFFX",),
    "william_blair": ("BGFIX",),
    "vaneck": ("GDX", "SMH", "MWMIX", "INIVX"),
    "wisdomtree": ("GTR", "WTPI", "XC"),
    "first_trust": ("BGLD", "FVD"),
    "dws": ("DBEF",),
    "aqr": ("AQGIX",),
    "causeway": ("CIVIX",),
    "alger": ("CHUSX",),
    "harding_loevner": ("HLMNX",),
    "matthews_asia": ("MAPTX",),
    "tcw": ("TGDIX",),
    "jensen": ("JENSX",),
    "american_beacon": ("AADEX",),
    "lazard": ("LZIEX",),
    "baird": ("BSVIX",),
    "gqg": ("GQEIX",),
    "lsv": ("LSVEX",),
    "hennessy": ("HFCSX",),
    "kinetics": ("WWNPX",),
    "meridian": ("MERDX",),
    "marsico": ("MFOCX",),
    "guidestone": ("GGEZX",),
    "diamond_hill": ("DHLAX",),
    "baillie_gifford": ("BGAKX",),
    "brandes": ("BGVIX",),
    "fam": ("FAMVX",),
    "driehaus": ("DMCRX",),
}


def estimate_feed_status(slug: str) -> str:
    return ESTIMATE_STATUS.get(slug, "unlisted")


def history_years(slug: str) -> list[int]:
    return list(HISTORY_YEARS.get(slug, ()))


def has_multi_year_history(slug: str) -> bool:
    return len(HISTORY_YEARS.get(slug, ())) >= 2


def performance_tickers(slug: str) -> list[str]:
    return list(PERFORMANCE_TICKERS.get(slug, ()))


def has_performance(slug: str) -> bool:
    return bool(PERFORMANCE_TICKERS.get(slug))
