from __future__ import annotations

from app.sources.american_funds import AmericanFundsSource
from app.sources.base import FundSource
from app.sources.families import (
    BlackRockSource,
    FidelitySource,
    GoldmanSachsSource,
    InvescoSource,
    JPMorganSource,
    PimcoSource,
    StateStreetSource,
    TRowePriceSource,
    VanguardSource,
)
from app.sources.next_tier import (
    AmundiSource,
    BnyMellonSource,
    ColumbiaThreadneedleSource,
    DimensionalSource,
    FranklinTempletonSource,
    MorganStanleySource,
    NorthernTrustSource,
    NuveenSource,
    SchwabSource,
    UbsSource,
)
from app.sources.third_tier import (
    AllianceBernsteinSource,
    AllspringSource,
    AmericanCenturySource,
    DodgeCoxSource,
    EatonVanceSource,
    FederatedHermesSource,
    JanusHendersonSource,
    LordAbbettSource,
    MfsSource,
    VirtusSource,
)
from app.sources.fourth_tier import (
    ArtisanSource,
    CalamosSource,
    FirstEagleSource,
    GmoSource,
    HartfordSource,
    JohnHancockSource,
    MacquarieSource,
    PrincipalSource,
    ThriventSource,
    WasatchSource,
)
from app.sources.fifth_tier import (
    GabelliSource,
    HarborSource,
    NationwideSource,
    NylifeSource,
    OakmarkSource,
    RoyceSource,
    TouchstoneSource,
    TweedySource,
    VictorySource,
    VoyaSource,
)

_ALIASES = {
    "american_funds": "american_funds",
    "american-funds": "american_funds",
    "americanfunds": "american_funds",
    "capital_group": "american_funds",
    "capital-group": "american_funds",
    "capitalgroup": "american_funds",
    "blackrock": "blackrock",
    "ishares": "blackrock",
    "i_shares": "blackrock",
    "vanguard": "vanguard",
    "fidelity": "fidelity",
    "state_street": "state_street",
    "statestreet": "state_street",
    "ssga": "state_street",
    "spdr": "state_street",
    "jpmorgan": "jpmorgan",
    "jp_morgan": "jpmorgan",
    "jpm": "jpmorgan",
    "goldman_sachs": "goldman_sachs",
    "goldman": "goldman_sachs",
    "gs": "goldman_sachs",
    "gsam": "goldman_sachs",
    "pimco": "pimco",
    "invesco": "invesco",
    "t_rowe_price": "t_rowe_price",
    "troweprice": "t_rowe_price",
    "t_rowe": "t_rowe_price",
    "trp": "t_rowe_price",
    "ubs": "ubs",
    "franklin_templeton": "franklin_templeton",
    "franklin": "franklin_templeton",
    "templeton": "franklin_templeton",
    "putnam": "franklin_templeton",
    "bny_mellon": "bny_mellon",
    "bny": "bny_mellon",
    "dreyfus": "bny_mellon",
    "nuveen": "nuveen",
    "tiaa": "nuveen",
    "northern_trust": "northern_trust",
    "northern": "northern_trust",
    "nt": "northern_trust",
    "ntam": "northern_trust",
    "morgan_stanley": "morgan_stanley",
    "msim": "morgan_stanley",
    "ms": "morgan_stanley",
    "schwab": "schwab",
    "charles_schwab": "schwab",
    "csim": "schwab",
    "dimensional": "dimensional",
    "dfa": "dimensional",
    "columbia_threadneedle": "columbia_threadneedle",
    "columbia": "columbia_threadneedle",
    "ameriprise": "columbia_threadneedle",
    "amundi": "amundi",
    "pioneer": "amundi",
    "victory_pioneer": "amundi",
    "allspring": "allspring",
    "wells_fargo": "allspring",
    "wfam": "allspring",
    "wells_fargo_am": "allspring",
    "janus_henderson": "janus_henderson",
    "janus": "janus_henderson",
    "american_century": "american_century",
    "dodge_cox": "dodge_cox",
    "dodge": "dodge_cox",
    "dodgeandcox": "dodge_cox",
    "dodgx": "dodge_cox",
    "mfs": "mfs",
    "lord_abbett": "lord_abbett",
    "lord": "lord_abbett",
    "lordabbett": "lord_abbett",
    "ab": "ab",
    "alliancebernstein": "ab",
    "alliance_bernstein": "ab",
    "federated_hermes": "federated_hermes",
    "federated": "federated_hermes",
    "virtus": "virtus",
    "eaton_vance": "eaton_vance",
    "eatonvance": "eaton_vance",
    "ev": "eaton_vance",
    "john_hancock": "john_hancock",
    "johnhancock": "john_hancock",
    "manulife": "john_hancock",
    "jh": "john_hancock",
    "jhi": "john_hancock",
    "principal": "principal",
    "principalam": "principal",
    "thrivent": "thrivent",
    "hartford": "hartford",
    "hartford_funds": "hartford",
    "macquarie": "macquarie",
    "delaware": "macquarie",
    "delaware_funds": "macquarie",
    "delaware_ivy": "macquarie",
    "first_eagle": "first_eagle",
    "firsteagle": "first_eagle",
    "fei": "first_eagle",
    "gmo": "gmo",
    "artisan": "artisan",
    "artisan_partners": "artisan",
    "calamos": "calamos",
    "wasatch": "wasatch",
    "harbor": "harbor",
    "harbor_capital": "harbor",
    "nationwide": "nationwide",
    "voya": "voya",
    "allianzgi": "voya",
    "allianz_gi": "voya",
    "oakmark": "oakmark",
    "harris": "oakmark",
    "harris_associates": "oakmark",
    "tweedy": "tweedy",
    "tweedy_browne": "tweedy",
    "tweedybrowne": "tweedy",
    "gabelli": "gabelli",
    "gamco": "gabelli",
    "royce": "royce",
    "royce_funds": "royce",
    "nylife": "nylife",
    "nyli": "nylife",
    "nylim": "nylife",
    "mainstay": "nylife",
    "new_york_life": "nylife",
    "touchstone": "touchstone",
    "victory": "victory",
    "vcm": "victory",
    "victory_capital": "victory",
}


def _sources() -> dict[str, FundSource]:
    ordered = [
        BlackRockSource(),
        VanguardSource(),
        FidelitySource(),
        StateStreetSource(),
        JPMorganSource(),
        GoldmanSachsSource(),
        AmericanFundsSource(),
        PimcoSource(),
        InvescoSource(),
        TRowePriceSource(),
        UbsSource(),
        FranklinTempletonSource(),
        BnyMellonSource(),
        NuveenSource(),
        NorthernTrustSource(),
        MorganStanleySource(),
        SchwabSource(),
        DimensionalSource(),
        ColumbiaThreadneedleSource(),
        AmundiSource(),
        AllspringSource(),
        JanusHendersonSource(),
        AmericanCenturySource(),
        DodgeCoxSource(),
        MfsSource(),
        LordAbbettSource(),
        AllianceBernsteinSource(),
        FederatedHermesSource(),
        VirtusSource(),
        EatonVanceSource(),
        JohnHancockSource(),
        PrincipalSource(),
        ThriventSource(),
        HartfordSource(),
        MacquarieSource(),
        FirstEagleSource(),
        GmoSource(),
        ArtisanSource(),
        CalamosSource(),
        WasatchSource(),
        HarborSource(),
        NationwideSource(),
        VoyaSource(),
        OakmarkSource(),
        TweedySource(),
        GabelliSource(),
        RoyceSource(),
        NylifeSource(),
        TouchstoneSource(),
        VictorySource(),
    ]
    return {source.slug: source for source in ordered}


def list_sources() -> list[FundSource]:
    return sorted(
        _sources().values(),
        key=lambda s: (s.aum_rank is None, s.aum_rank or 99, s.slug),
    )


def get_source(slug: str) -> FundSource:
    sources = _sources()
    key = _ALIASES.get(slug.strip().lower().replace(" ", "_"), slug.strip().lower().replace(" ", "_"))
    if key not in sources:
        known = ", ".join(sorted(sources))
        raise KeyError(f"Unknown fund family '{slug}'. Registered: {known}")
    return sources[key]


def resolve_slug(value: str | None) -> str | None:
    if not value:
        return None
    key = value.strip().lower().replace(" ", "_")
    if key in _ALIASES:
        return _ALIASES[key]
    sources = _sources()
    if key in sources:
        return key
    return None


def resolve_families(fund_family: str) -> list[FundSource]:
    if fund_family.strip().lower() in {"all", "*"}:
        return [s for s in list_sources() if s.implemented]
    return [get_source(fund_family)]
