from __future__ import annotations

from functools import lru_cache

from app.sources.american_funds import AmericanFundsSource
from app.sources.base import FundSource
from app.sources.families import (
    BlackRockSource,
    FidelitySource,
    GoldmanSachsSource,
    InvescoSource,
    JPMorganSource,
    PimcoSource,
    StateStreetSource,
    TRowePriceSource,
    VanguardSource,
)
from app.sources.next_tier import (
    AmundiSource,
    BnyMellonSource,
    ColumbiaThreadneedleSource,
    DimensionalSource,
    FranklinTempletonSource,
    MorganStanleySource,
    NorthernTrustSource,
    NuveenSource,
    SchwabSource,
    UbsSource,
)
from app.sources.third_tier import (
    AllianceBernsteinSource,
    AllspringSource,
    AmericanCenturySource,
    DodgeCoxSource,
    EatonVanceSource,
    FederatedHermesSource,
    JanusHendersonSource,
    LordAbbettSource,
    MfsSource,
    VirtusSource,
)
from app.sources.fourth_tier import (
    ArtisanSource,
    CalamosSource,
    FirstEagleSource,
    GmoSource,
    HartfordSource,
    JohnHancockSource,
    MacquarieSource,
    PrincipalSource,
    ThriventSource,
    WasatchSource,
)
from app.sources.fifth_tier import (
    GabelliSource,
    HarborSource,
    NationwideSource,
    NylifeSource,
    OakmarkSource,
    RoyceSource,
    TouchstoneSource,
    TweedySource,
    VictorySource,
    VoyaSource,
)
from app.sources.sixth_tier import (
    AlgerSource,
    AqrSource,
    BrownAdvisorySource,
    CausewaySource,
    HardingLoevnerSource,
    MatthewsAsiaSource,
    SeiSource,
    FirstTrustSource,
    VaneckSource,
    WilliamBlairSource,
    WisdomtreeSource,
)
from app.sources.seventh_tier import (
    BridgewaySource,
    ChamplainSource,
    DavisSource,
    DiamondHillSource,
    DriehausSource,
    HotchkisWileySource,
    JensenSource,
    MarsicoSource,
    OsterweisSource,
    TcwSource,
)
from app.sources.eighth_tier import (
    ArielSource,
    BairdSource,
    BuffaloSource,
    FmiSource,
    GqgSource,
    HeartlandSource,
    ImpaxSource,
    LongleafSource,
    PrimecapSource,
    ThirdAvenueSource,
)
from app.sources.ninth_tier import (
    AmericanBeaconSource,
    BaillieGiffordSource,
    BostonTrustSource,
    BrandesSource,
    FamSource,
    GrandeurPeakSource,
    HennessySource,
    KineticsSource,
    MairsPowerSource,
    MeridianSource,
)
from app.sources.tenth_tier import (
    BostonPartnersSource,
    HomesteadSource,
    LazardSource,
    LkcmSource,
    LsvSource,
    MadisonSource,
    ManningNapierSource,
    OberweisSource,
    RiverparkSource,
    WestwoodSource,
)
from app.sources.dws import DwsSource
from app.sources.catalyst import CatalystSource
from app.sources.ark import ArkSource
from app.sources.eleventh_tier import (
    AmgSource,
    ConestogaSource,
    GuidestoneSource,
    HodgesSource,
    KopernikSource,
    LocorrSource,
    PermanentPortfolioSource,
    TimothyPlanSource,
    TocquevilleSource,
    ValueLineSource,
)

_ALIASES = {
    "american_funds": "american_funds",
    "american-funds": "american_funds",
    "americanfunds": "american_funds",
    "capital_group": "american_funds",
    "capital-group": "american_funds",
    "capitalgroup": "american_funds",
    "blackrock": "blackrock",
    "ishares": "blackrock",
    "i_shares": "blackrock",
    "vanguard": "vanguard",
    "fidelity": "fidelity",
    "state_street": "state_street",
    "statestreet": "state_street",
    "ssga": "state_street",
    "spdr": "state_street",
    "jpmorgan": "jpmorgan",
    "jp_morgan": "jpmorgan",
    "jpm": "jpmorgan",
    "goldman_sachs": "goldman_sachs",
    "goldman": "goldman_sachs",
    "gs": "goldman_sachs",
    "gsam": "goldman_sachs",
    "pimco": "pimco",
    "invesco": "invesco",
    "t_rowe_price": "t_rowe_price",
    "troweprice": "t_rowe_price",
    "t_rowe": "t_rowe_price",
    "trp": "t_rowe_price",
    "ubs": "ubs",
    "franklin_templeton": "franklin_templeton",
    "franklin": "franklin_templeton",
    "templeton": "franklin_templeton",
    "putnam": "franklin_templeton",
    "bny_mellon": "bny_mellon",
    "bny": "bny_mellon",
    "dreyfus": "bny_mellon",
    "nuveen": "nuveen",
    "tiaa": "nuveen",
    "northern_trust": "northern_trust",
    "northern": "northern_trust",
    "nt": "northern_trust",
    "ntam": "northern_trust",
    "morgan_stanley": "morgan_stanley",
    "msim": "morgan_stanley",
    "ms": "morgan_stanley",
    "schwab": "schwab",
    "charles_schwab": "schwab",
    "csim": "schwab",
    "dimensional": "dimensional",
    "dfa": "dimensional",
    "columbia_threadneedle": "columbia_threadneedle",
    "columbia": "columbia_threadneedle",
    "ameriprise": "columbia_threadneedle",
    "amundi": "amundi",
    "pioneer": "amundi",
    "victory_pioneer": "amundi",
    "allspring": "allspring",
    "wells_fargo": "allspring",
    "wfam": "allspring",
    "wells_fargo_am": "allspring",
    "janus_henderson": "janus_henderson",
    "janus": "janus_henderson",
    "american_century": "american_century",
    "dodge_cox": "dodge_cox",
    "dodge": "dodge_cox",
    "dodgeandcox": "dodge_cox",
    "dodgx": "dodge_cox",
    "mfs": "mfs",
    "lord_abbett": "lord_abbett",
    "lord": "lord_abbett",
    "lordabbett": "lord_abbett",
    "ab": "ab",
    "alliancebernstein": "ab",
    "alliance_bernstein": "ab",
    "federated_hermes": "federated_hermes",
    "federated": "federated_hermes",
    "virtus": "virtus",
    "eaton_vance": "eaton_vance",
    "eatonvance": "eaton_vance",
    "ev": "eaton_vance",
    "john_hancock": "john_hancock",
    "johnhancock": "john_hancock",
    "manulife": "john_hancock",
    "jh": "john_hancock",
    "jhi": "john_hancock",
    "principal": "principal",
    "principalam": "principal",
    "thrivent": "thrivent",
    "hartford": "hartford",
    "hartford_funds": "hartford",
    "macquarie": "macquarie",
    "delaware": "macquarie",
    "delaware_funds": "macquarie",
    "delaware_ivy": "macquarie",
    "first_eagle": "first_eagle",
    "firsteagle": "first_eagle",
    "fei": "first_eagle",
    "gmo": "gmo",
    "artisan": "artisan",
    "artisan_partners": "artisan",
    "calamos": "calamos",
    "wasatch": "wasatch",
    "harbor": "harbor",
    "harbor_capital": "harbor",
    "nationwide": "nationwide",
    "voya": "voya",
    "allianzgi": "voya",
    "allianz_gi": "voya",
    "oakmark": "oakmark",
    "harris": "oakmark",
    "harris_associates": "oakmark",
    "tweedy": "tweedy",
    "tweedy_browne": "tweedy",
    "tweedybrowne": "tweedy",
    "gabelli": "gabelli",
    "gamco": "gabelli",
    "royce": "royce",
    "royce_funds": "royce",
    "nylife": "nylife",
    "nyli": "nylife",
    "nylim": "nylife",
    "mainstay": "nylife",
    "new_york_life": "nylife",
    "touchstone": "touchstone",
    "victory": "victory",
    "vcm": "victory",
    "victory_capital": "victory",
    "sei": "sei",
    "seic": "sei",
    "brown_advisory": "brown_advisory",
    "brown": "brown_advisory",
    "william_blair": "william_blair",
    "blair": "william_blair",
    "wbim": "william_blair",
    "vaneck": "vaneck",
    "van_eck": "vaneck",
    "wisdomtree": "wisdomtree",
    "wt": "wisdomtree",
    "first_trust": "first_trust",
    "firsttrust": "first_trust",
    "ft": "first_trust",
    "ftportfolios": "first_trust",
    "dws": "dws",
    "xtrackers": "dws",
    "xtracker": "dws",
    "deutsche": "dws",
    "deutsche_bank": "dws",
    "dbx": "dws",
    "dbx_advisors": "dws",
    "dws_funds": "dws",
    "dws_mutual_funds": "dws",
    "catalyst": "catalyst",
    "catalyst_funds": "catalyst",
    "catalystmf": "catalyst",
    "catalyst_mutual_funds": "catalyst",
    "catalyst_mf": "catalyst",
    "catalyst_millburn": "catalyst",
    "ark": "ark",
    "ark_invest": "ark",
    "ark_funds": "ark",
    "arkinvest": "ark",
    "aqr": "aqr",
    "causeway": "causeway",
    "alger": "alger",
    "fred_alger": "alger",
    "fredalger": "alger",
    "harding_loevner": "harding_loevner",
    "harding": "harding_loevner",
    "hl": "harding_loevner",
    "matthews_asia": "matthews_asia",
    "matthews": "matthews_asia",
    "tcw": "tcw",
    "bridgeway": "bridgeway",
    "jensen": "jensen",
    "diamond_hill": "diamond_hill",
    "diamond": "diamond_hill",
    "champlain": "champlain",
    "cip": "champlain",
    "cipvt": "champlain",
    "driehaus": "driehaus",
    "hotchkis": "hotchkis",
    "hw": "hotchkis",
    "hwcm": "hotchkis",
    "hotchkis_wiley": "hotchkis",
    "marsico": "marsico",
    "osterweis": "osterweis",
    "ost": "osterweis",
    "davis": "davis",
    "davis_funds": "davis",
    "primecap": "primecap",
    "odyssey": "primecap",
    "primecap_odyssey": "primecap",
    "ariel": "ariel",
    "baird": "baird",
    "longleaf": "longleaf",
    "southeastern": "longleaf",
    "buffalo": "buffalo",
    "gqg": "gqg",
    "third_avenue": "third_avenue",
    "thirdave": "third_avenue",
    "tav": "third_avenue",
    "heartland": "heartland",
    "fmi": "fmi",
    "fmimgt": "fmi",
    "impax": "impax",
    "pax": "impax",
    "impaxam": "impax",
    "american_beacon": "american_beacon",
    "beacon": "american_beacon",
    "baillie_gifford": "baillie_gifford",
    "baillie": "baillie_gifford",
    "bg": "baillie_gifford",
    "brandes": "brandes",
    "mairs_power": "mairs_power",
    "mairs": "mairs_power",
    "mairsandpower": "mairs_power",
    "boston_trust": "boston_trust",
    "walden": "boston_trust",
    "boston_trust_walden": "boston_trust",
    "grandeur_peak": "grandeur_peak",
    "grandeur": "grandeur_peak",
    "hennessy": "hennessy",
    "fam": "fam",
    "fenimore": "fam",
    "meridian": "meridian",
    "arrowmark": "meridian",
    "kinetics": "kinetics",
    "horizon_kinetics": "kinetics",
    "lazard": "lazard",
    "lam": "lazard",
    "manning_napier": "manning_napier",
    "manning": "manning_napier",
    "manningandnapier": "manning_napier",
    "westwood": "westwood",
    "whg": "westwood",
    "boston_partners": "boston_partners",
    "bostonpartners": "boston_partners",
    "robeco": "boston_partners",
    "homestead": "homestead",
    "nreca": "homestead",
    "madison": "madison",
    "madison_funds": "madison",
    "lsv": "lsv",
    "lsvasset": "lsv",
    "lkcm": "lkcm",
    "luther_king": "lkcm",
    "oberweis": "oberweis",
    "oam": "oberweis",
    "riverpark": "riverpark",
    "rp": "riverpark",
    "amg": "amg",
    "amg_funds": "amg",
    "amgfunds": "amg",
    "guidestone": "guidestone",
    "guide_stone": "guidestone",
    "value_line": "value_line",
    "valueline": "value_line",
    "vl": "value_line",
    "permanent_portfolio": "permanent_portfolio",
    "prpfx": "permanent_portfolio",
    "conestoga": "conestoga",
    "kopernik": "kopernik",
    "locorr": "locorr",
    "timothy_plan": "timothy_plan",
    "timothy": "timothy_plan",
    "hodges": "hodges",
    "tocqueville": "tocqueville",
}


@lru_cache(maxsize=1)
def _sources() -> dict[str, FundSource]:
    ordered = [
        BlackRockSource(),
        VanguardSource(),
        FidelitySource(),
        StateStreetSource(),
        JPMorganSource(),
        GoldmanSachsSource(),
        AmericanFundsSource(),
        PimcoSource(),
        InvescoSource(),
        TRowePriceSource(),
        UbsSource(),
        FranklinTempletonSource(),
        BnyMellonSource(),
        NuveenSource(),
        NorthernTrustSource(),
        MorganStanleySource(),
        SchwabSource(),
        DimensionalSource(),
        ColumbiaThreadneedleSource(),
        AmundiSource(),
        AllspringSource(),
        JanusHendersonSource(),
        AmericanCenturySource(),
        DodgeCoxSource(),
        MfsSource(),
        LordAbbettSource(),
        AllianceBernsteinSource(),
        FederatedHermesSource(),
        VirtusSource(),
        EatonVanceSource(),
        JohnHancockSource(),
        PrincipalSource(),
        ThriventSource(),
        HartfordSource(),
        MacquarieSource(),
        FirstEagleSource(),
        GmoSource(),
        ArtisanSource(),
        CalamosSource(),
        WasatchSource(),
        HarborSource(),
        NationwideSource(),
        VoyaSource(),
        OakmarkSource(),
        TweedySource(),
        GabelliSource(),
        RoyceSource(),
        NylifeSource(),
        TouchstoneSource(),
        VictorySource(),
        SeiSource(),
        BrownAdvisorySource(),
        WilliamBlairSource(),
        VaneckSource(),
        WisdomtreeSource(),
        FirstTrustSource(),
        DwsSource(),
        CatalystSource(),
        ArkSource(),
        AqrSource(),
        CausewaySource(),
        AlgerSource(),
        HardingLoevnerSource(),
        MatthewsAsiaSource(),
        TcwSource(),
        BridgewaySource(),
        JensenSource(),
        DiamondHillSource(),
        ChamplainSource(),
        DriehausSource(),
        HotchkisWileySource(),
        MarsicoSource(),
        OsterweisSource(),
        DavisSource(),
        PrimecapSource(),
        ArielSource(),
        BairdSource(),
        LongleafSource(),
        BuffaloSource(),
        GqgSource(),
        ThirdAvenueSource(),
        HeartlandSource(),
        FmiSource(),
        ImpaxSource(),
        AmericanBeaconSource(),
        BaillieGiffordSource(),
        BrandesSource(),
        MairsPowerSource(),
        BostonTrustSource(),
        GrandeurPeakSource(),
        HennessySource(),
        FamSource(),
        MeridianSource(),
        KineticsSource(),
        LazardSource(),
        ManningNapierSource(),
        WestwoodSource(),
        BostonPartnersSource(),
        HomesteadSource(),
        MadisonSource(),
        LsvSource(),
        LkcmSource(),
        OberweisSource(),
        RiverparkSource(),
        AmgSource(),
        GuidestoneSource(),
        ValueLineSource(),
        PermanentPortfolioSource(),
        ConestogaSource(),
        KopernikSource(),
        LocorrSource(),
        TimothyPlanSource(),
        HodgesSource(),
        TocquevilleSource(),
    ]
    return {source.slug: source for source in ordered}


def list_sources() -> list[FundSource]:
    return sorted(
        _sources().values(),
        key=lambda s: (s.aum_rank is None, s.aum_rank or 99, s.slug),
    )


@lru_cache(maxsize=1)
def registered_family_slugs() -> tuple[str, ...]:
    """Stable slug list for /health. Avoids reconstructing 114 sources per probe."""
    return tuple(source.slug for source in list_sources())


def get_source(slug: str) -> FundSource:
    sources = _sources()
    key = _ALIASES.get(slug.strip().lower().replace(" ", "_"), slug.strip().lower().replace(" ", "_"))
    if key not in sources:
        known = ", ".join(sorted(sources))
        raise KeyError(f"Unknown fund family '{slug}'. Registered: {known}")
    return sources[key]


def resolve_slug(value: str | None) -> str | None:
    if not value:
        return None
    key = value.strip().lower().replace(" ", "_")
    if key in _ALIASES:
        return _ALIASES[key]
    sources = _sources()
    if key in sources:
        return key
    return None


def resolve_families(fund_family: str) -> list[FundSource]:
    if fund_family.strip().lower() in {"all", "*"}:
        return [s for s in list_sources() if s.implemented]
    return [get_source(fund_family)]
